FROM golang:1.24-alpine as builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o producer ./cmd/producer/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/producer /app/producer
COPY ./config /app/config
CMD ["/app/producer"]
