FROM golang:1.24-alpine as builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o receiver ./cmd/receiver/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/receiver /app/receiver
COPY ./config /app/config
EXPOSE 8080
CMD ["/app/receiver"]
