// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/AIdenTale/go-hack.git/internal/app/config"
	"github.com/AIdenTale/go-hack.git/internal/service"
	"github.com/AIdenTale/go-hack.git/pkg/db"
	"github.com/AIdenTale/go-hack.git/pkg/logger"
	"go.uber.org/zap"
)

// Injectors from wire.go:

// InitializeApp инициализирует зависимости приложения через wire.
func InitializeApp(configPath string) (*App, error) {
	configConfig, err := config.LoadConfig(configPath)
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.New(configPath)
	if err != nil {
		return nil, err
	}
	postgres, err := db.New(configConfig)
	if err != nil {
		return nil, err
	}
	pregnantDatPostgresRepository := db.NewPregnantDatPostgresRepository(postgres)
	pregnantDatService := service.NewPregnantDatService(pregnantDatPostgresRepository)
	dataPostgresRepository := db.NewDataPostgresRepository(postgres)
	dataService := service.NewDataService(dataPostgresRepository)
	app := newApp(configConfig, zapLogger, postgres, pregnantDatService, dataService)
	return app, nil
}

// wire.go:

func newApp(cfg *config.Config, logger2 *zap.Logger, pg *db.Postgres,
	pregnantService *service.PregnantDatService,
	dataService *service.DataService) *App {
	return &App{
		Config:             cfg,
		Logger:             logger2,
		Postgres:           pg,
		PregnantDatService: pregnantService,
		DataService:        dataService,
	}
}

// AppDeps агрегирует зависимости приложения для внедрения через wire.
type App struct {
	Config *config.Config
	Logger *zap.Logger

	Postgres           *db.Postgres
	PregnantDatService *service.PregnantDatService
	DataService        *service.DataService
}
