Postgres:
  Host: postgres
  Port: 5432
  User: gohack
  Password: gohack
  DBname: gohack
  sslmode: disable

echo:
  address: ":8080"

logger:
  level: "info"

ml:
  base_url: "http://ml:8000"  # URL ML сервиса в docker-compose сети
  update_interval: 10  # интервал обновления в секундах
